command:
  - "python"
  - "app.py"

env:
  - name: LAKEBASE_SECRET_SCOPE
    value: "weather"
  - name: LAKEBASE_SECRET_KEY
    value: "lakebase-url"
  - name: NWS_USER_AGENT
    value: "vector-weather-retrieval-service (set-your-contact-email@example.com)"
  - name: WEATHER_EMBEDDING_MODEL
    value: "sentence-transformers/all-MiniLM-L6-v2"
